routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'DashboardController@index')->name('/');

//Route::get('/profile', 'UsersController');

Route::resource('users', 'UsersController');
Route::resource('notifications', 'NotificationsController');
Route::resource('sites', 'SitesController');
Route::resource('rooms', 'RoomsController');
Route::get('/ccs', 'CcsController@index')->name('ccs.index');

Route::patch('/users/{user}/change-is-active', 'UsersController@changeIsActive');

Route::get('/users/{user}/roles/add', 'UserRolesController@create');
Route::post('/users/{user}/roles', 'UserRolesController@store');
Route::delete('/users/{user}/roles/{role}/delete', 'UserRolesController@destroy');

Route::get('/users/{user}/rooms/add', 'RoomAccessPermissionsController@create');
Route::post('/users/{user}/rooms', 'RoomAccessPermissionsController@store');
Route::delete('/users/{user}/rooms/{room}/delete', 'RoomAccessPermissionsController@destroy');

Route::get('/users/{user}/notifications/add', 'NotificationSubscriptionsController@create');
Route::post('/users/{user}/notifications', 'NotificationSubscriptionsController@store');
Route::delete('/users/{user}/notifications/{notification}/delete', 'NotificationSubscriptionsController@destroy');

Route::get('/sites/{site}/rooms/create', 'RoomsController@create')->name('sites');
Route::post('/sites/{site}/rooms', 'RoomsController@store')->name('sites');
Route::get('/sites/{site}/rooms/{room}/edit', 'RoomsController@edit')->name('sites');
Route::patch('/sites/{site}/rooms/{room}', 'RoomsController@update')->name('sites');
Route::get('/sites/{site}/rooms/{room}', 'RoomsController@show')->name('sites');

Route::get('/units', 'SystemUnitsController@index')->name('units.index');

Route::get('/rooms/{room}/units/add', 'SystemUnitsController@create');
Route::post('/rooms/{room}/units', 'SystemUnitsController@store');
Route::get('/units/{unit}/edit', 'SystemUnitsController@edit')->name('units');
Route::patch('/units/{unit}', 'SystemUnitsController@update')->name('units');
Route::get('/units/{unit}', 'SystemUnitsController@show')->name('units');

Route::patch('/units/{unit}/change-is-active', 'SystemUnitsController@changeIsActive');

Route::get('/verifications', 'VerificationsController@index')->name('verifications.index');
Route::patch('/verifications/{verification}/verify', 'VerificationsController@verify');

//Route::post('/login', '')->name('login');
//Route::post('/logout', '')->name('logout');
Auth::routes();

resources/views/error.blade.php
@if($errors->any())

    <div class="alert alert-danger">
        <strong>Error!</strong> Correct the following error(s) and try again.

        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>

@endif

resources/views/menu.blade.php
<nav class="navbar fixed-top navbar-expand-sm bg-dark navbar-dark shadow">
    <a class="navbar-brand" href="{{ route('/') }}">HOS - Home and Office Security</a>
        @guest
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{{ route('login') }}">Login</a></li>
            </ul>
        @else
            <ul class="navbar-nav">
                <li class="nav-item {{ request()->routeIs('/*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('/') }}">Dashboard</a></li>
                @can('index', App\User::class)
                    <li class="nav-item {{ request()->routeIs('users*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('users.index') }}">Users</a></li>
                @endcan
                <li class="nav-item {{ request()->routeIs('sites*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('sites.index') }}">Sites & Rooms</a></li>
                <li class="nav-item {{ request()->routeIs('units*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('units.index') }}">Units</a></li>
                <li class="nav-item {{ request()->routeIs('verifications*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('verifications.index') }}">Verifications</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mr-2"><span class="navbar-text">Hi, {{ Auth::user()->firstname }}!</span></li>
                <li class="nav-item"><a class="nav-link" href="/users/{{ Auth::user()->id }}">My Profile</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit()">Logout</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: inline;">
                        @csrf
                    </form>
                </li>
            </ul>
        @endguest
</nav>